version: "3"
networks:
  global4crm:
services:
  web:
    container_name: global4crm_web
    networks:
      - global4crm
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./src:/var/www/html
      - ./configs/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80


